### PR TITLE
Update terser@5.5.1

### PR DESCRIPTION
**Pull request by pioug**
I spent some time migrating to terser v5. The main difference is that `minify()` is asynchronous. I reused the same pattern as in https://github.com/posthtml/htmlnano/blob/master/lib/modules/minifyConditionalComments.es6. I replaced the `tree.walk()` with a for loop to be able to use with async/await. Unit tests look good 👍 

The Node 10 requirement seems to match with this project too.

I am wondering if you would be interested because other html minifiers are blocked on older version of JS minifier too (https://github.com/kangax/html-minifier/issues/1077, https://github.com/terser/html-minifier-terser/issues/46).

### CODE REVIEW

**Comment by SukkaW** [comment]
IMHO, instead of reusing the pattern from `minifyConditionComment`, I'd prefer the pattern from [`minifySvg`](https://github.com/posthtml/htmlnano/blob/41b4e3fa02cc9c7770a711322e0ce2082c3b4cd0/lib/modules/minifySvg.es6) (`Promise.all`). This should have better performance.

**Comment by pioug** [comment]
@SukkaW Thanks for reviewing. I replaced the "for loop" with `tree.map(...)` so nodes will be processed concurrently. I thing that's the most we can get?

**Review by SukkaW — COMMENTED** [review]
Is it possible to avoid using `async` & `await`?

`async & await` *looks* great, but it is slower than traditional *thenable* Promise.

**Comment by pioug** [comment]
I replaced async/await. Not sure if can be shorter/cleaner while respecting the same sequence.

Can you point me to any data/infos showing that promises are faster? I want to know if other projects could benefit from that.

**Comment by maltsev** [comment]
@pioug I totally forgot about your PR and implemented the upgrade separately in d56b118937ad48bd51a3c4b5594d24d60fe9daf1 I'm sorry about that, I should have reviewed and merged your PR instead :-/ 

My implementation turned out to be a bit short, though.

**Comment by pioug** [comment]
Great! As long as it's updated 🙌

**Comment by maltsev** [comment]
I just released the new version 0.2.9 with this update.

**Pull request closed without merging**
