### PR TITLE
feat: convert HTMLNano to Es Modules

### LINKED ISSUE #259: Do not use dynamic `require` to load modules
htmlnano uses dynamic `require` to load the modules. However, many tools do not support `dynamic requires` anymore. This should be changed to `await import()` to be compatible with modern tooling.

https://github.com/posthtml/htmlnano/blob/a0d64a8ca86a099599acdd05c26483fb6f1613ad/lib/htmlnano.es6#L82

I created `astro-htmlnano` to allow minifying Astro files using htmlnano, however, due to the usage of `require` in htmlnano, the package doesn't work.
https://github.com/aminya/astro-plugins/tree/main/packages/astro-htmlnano

### PR DESCRIPTION
**Pull request by aminya**
Fixes #259 

This removes all the usage of commonjs from HTMLNano replacing it with standard ES modules. The optional dependencies are now imported using dynamic imports. So, the functionality will be preserved.

All the current tests pass. I added commonjs compatibility tests to make sure nothing breaks.

The minify function returned by htmlnano is now async due to the dynamic import. `posthtml` should await this promise. Based on the tests, posthtml already does this, so there should not be an issue.

This change allows adoption of HTMLNano to new projects that only work with pure ES modules.

Tests passing:
image

Backwards compatibility tests:
image

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
I am not a fan of pure ESM package, as well as the existing community. htmlnano is still used by toolchain/bundler that uses CommonJS. Would you like to make it a dual ESM/CJS?

**Comment by aminya** [comment]
> I am not a fan of pure ESM package, as well as the existing community. htmlnano is still used by toolchain/bundler that uses CommonJS. Would you like to make it a dual ESM/CJS?

If you notice, I have kept the package backwards compatible. The main entry still points to `.cjs` file compiled by babel from the ES module.

**Comment by aminya** [comment]
Could you approve the CI?

**Comment by maltsev** [comment]
> Could you approve the CI?

Sure. Just did.

**Comment by aminya** [comment]
Thank you. This PR is ready. Let me know if there is anything else to be done here.

**Comment by maltsev** [comment]
@SukkaW what do you think, can it be merged now?

**Comment by aminya** [comment]
This pull request is ready, but I made some changes to the Babel plugin responsible for `.cjs` extension backwards compatibility, making the output more efficient.

https://github.com/silane/babel-plugin-replace-import-extension/pull/9

Depending on the timing of the merges, I'll either update this PR or make a new PR to htmlnano with the improvement.

**Comment by aminya** [comment]
I published my fork of the babel plugin to unblock us. Now, the dynamic imports can be optimized by bundlers (e.g. for usage as an Astro plugin) and the `cjs` output is very efficient!

**Comment by maltsev** [comment]
Thanks! 

@aminya I guess this could be released as a minor version or patch as it doesn't contain any backward incompatible changes?

**Comment by aminya** [comment]
> Thanks! 
> 
> @aminya I guess this could be released as a minor version or patch as it doesn't contain any backward incompatible changes? 

You are welcome!

I'd go with a minor version as the addition is a new feature. But it should be backwards compatible.

**Comment by maltsev** [comment]
Released: https://github.com/posthtml/htmlnano/releases/tag/2.1.0

**Pull request merged**
