### PR TITLE
Feat: normalize attribute

### PR DESCRIPTION
**Pull request by SukkaW**
New module added.

### CODE REVIEW

**Review by maltsev — APPROVED** [review]
It's better to add docs for the new module to `docs/docs`. Because the current version 1.0.1 doesn't have it.

**Comment by SukkaW** [comment]
> It's better to add docs for the new module to `docs/docs`. Because the current version 1.0.1 doesn't have it.

Oh I didn't notice that docs are versioned. I will fix it.

**Review by maltsev — APPROVED** [review]
👍

**Comment by maltsev** [comment]
No problem :-)

Thanks for adding a lot of new features! I'll release a new version this weekend.

**Pull request merged**
