### PR TITLE
Fix SVGO plugin usage

### LINKED ISSUE #150: "extendDefaultPlugins" utility is deprecated
I'm getting this message in console:

```
"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}
```

Can we fix this?

### PR DESCRIPTION
**Pull request by thien-do**
Fix #150

### CODE REVIEW

**Comment by maltsev** [comment]
Thanks for the PR!

There are still several places where `extendDefaultPlugins` is used. Can you please update them as well?

```
docs/versioned_docs/version-1.0.0/050-modules.md
331:        plugins: extendDefaultPlugins([

test/modules/minifySvg.js
1:import { extendDefaultPlugins } from 'svgo';
63:                    plugins: extendDefaultPlugins([

docs/docs/050-modules.md
331:        plugins: extendDefaultPlugins([
```

**Comment by maltsev** [comment]
Also, it seems that the tests haven't been run for these changes. I change the config (https://github.com/posthtml/htmlnano/commit/a08931a4747094aedf2510f36e8e114269ece3f4), maybe can you merge these changes to your feature branch and push to Github?

**Comment by thien-do** [comment]
oh ok let me try :D I used the web editor previously. Look like I need to clone it now

**Comment by maltsev** [comment]
This has been fixed in #153

**Pull request closed without merging**
