### PR TITLE
Minify JS within <script type="module">

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Review by SukkaW — COMMENTED** [review]
I am not a reviewer, but FWIW the PR LGTM.

**Comment by Scrum** [comment]
@maltsev ping

**Review by maltsev — APPROVED** [review]
👍

**Comment by maltsev** [comment]
@Scrum thanks for implementing it! I just renamed the PR name, so it better reflects the changes made.

For reference: this is related to issue #134

**Pull request merged**
